version: "3"
services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./.docker/dev/go/Dockerfile
    volumes:
      - .:/app
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8082:8082
      - 6060:6060
    restart: always
